databases:
  - name: censusdb
    plan: free
    databaseName: census
    user: wc

services:
  - type: web
    plan: free
    name: FairMapAI
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn fairmapai.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: censusdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4