# Generated by Django 5.0.1 on 2024-10-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('district', models.IntegerField()),
                ('republican_votes', models.IntegerField()),
                ('democratic_votes', models.IntegerField()),
                ('area', models.FloatField()),
                ('perimeter', models.FloatField()),
                ('congress', models.IntegerField()),
                ('party', models.CharField(choices=[('R', 'Republican'), ('D', 'Democratic')], default='', max_length=1)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censusapi.state')),
            ],
        ),
    ]
